apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmas-deployment
  labels:
    app: xmas
    uri: xmas.algosup.com
spec:
  # ! Explicitly setting this field to 0, will result in cleaning up all the history of your Deployment thus that Deployment will not be able to roll back
  #revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: xmas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 69
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: xmas
    spec:
      containers:
      - name: xmas
        image: xmasimages.azurecr.io/xmas-image:latest
        imagePullPolicy: Always
        resources:
        # Requests and limits are mendatory for AKS
          requests:
            cpu: 125m
            memory: 32Mi
          limits:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 80